// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/*.tsx";

const manifest = {
  routes: {
    "./routes/*.tsx": $0,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
